- name: Install development setup
  hosts: localhost
  connection: local
  module_defaults:
    community.general.homebrew:
      path: /opt/homebrew/bin
  tasks:
    - name: Set common roles
      ansible.builtin.set_fact:
        use_sudo: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
        roles:
          - zsh
          - oh-my-zsh
          - tmux
          - environment
          - alacritty
          - pyenv
          - neovim
        roles_macos:
          - yabai
          - spacebar
          - skhd
    - name: Set facts for MacOS
      ansible.builtin.set_fact:
        use_sudo: no
      when: ansible_system == 'Darwin'
    - name: Run common roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
    - name: Run MacOS roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles_macos }}"
      when: ansible_system == 'Darwin'
