- name: Install development setup
  hosts: localhost
  connection: local
  module_defaults:
    community.general.homebrew:
      path: /opt/homebrew/bin
  tasks:
    - name: Set common roles
      ansible.builtin.set_fact:
        use_sudo: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
        components:
          - llvm
          - zsh
          - parallel
          - tmux
          - environment
          - kitty
          - ghostty
          - pyenv
          - pre-commit
          - npm
          - neovim
          - direnv
          - jq
          - fd
          - fzf
          - ripgrep
          - aws
          - git
          - watson
          - rust
          - aider
        components_macos:
          - yabai
          - spacebar
          - sketchybar
          - aerospace
          - skhd
    - name: Determine whether to use sudo
      ansible.builtin.set_fact:
        use_sudo: "{{ 'no' if ansible_system == 'Darwin' else 'yes' }}"
    - name: Install stow
      ansible.builtin.package:
        state: present
        name: stow
      become: "{{ use_sudo }}"
    - name: Run common roles
      ansible.builtin.include_role:
        name: "{{ component }}"
      loop_control:
        loop_var: component
      with_items: "{{ components }}"
    - name: Run MacOS roles
      ansible.builtin.include_role:
        name: "{{ component }}"
      loop_control:
        loop_var: component
      with_items: "{{ components_macos }}"
      when: ansible_system == 'Darwin'
