- name: Install development setup
  hosts: localhost
  connection: local
  module_defaults:
    community.general.homebrew:
      path: /opt/homebrew/bin
  tasks:
    - name: Set common roles
      ansible.builtin.set_fact:
        use_sudo: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
        roles:
          - llvm
          - zsh
          - parallel
          - oh-my-zsh
          - tmux
          - environment
          - alacritty
          - pyenv
          - pre-commit
          - neovim
          - direnv
          - jq
          - fd
        roles_macos:
          - yabai
          - spacebar
          - skhd
    - name: Determine whether to use sudo
      ansible.builtin.set_fact:
        use_sudo: "{{ 'no' if ansible_system=='Darwin' else 'yes' }}"
    - name: Install stow
      ansible.builtin.package:
        state: present
        name: stow
      become: "{{ use_sudo }}"
    - name: Run common roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
    - name: Run MacOS roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles_macos }}"
      when: ansible_system == 'Darwin'
    - debug:
        var: felixws_pyenv
