require("felixws.set")
require("felixws.lazy")
require("felixws.color")
require("felixws.python")
require("felixws.aucmds")
require("felixws.plugins")
require("felixws.commands")
require("felixws.keymaps")
