require("felixws.set")
require("felixws.lazy")
require("felixws.python")
require("felixws.aucmds")
require("felixws.lsp")
require("felixws.cmp")
require("felixws.plugins")
require("felixws.commands")
