- name: Install yabai
  ansible.builtin.package:
    state: present
    name: yabai
- name: Install stow
  ansible.builtin.package:
    state: present
    name: stow
  become: "{{ use_sudo }}"
- name: Stow yabai
  ansible.builtin.command:
    cmd: stow yabai --target=$HOME --verbose=2
    chdir: "{{ ansible_user_dir }}/.dotfiles"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
