- name: Install yabai
  ansible.builtin.package:
    state: present
    name: koekeishiya/formulae/yabai
- name: Stow yabai
  ansible.builtin.command:
    cmd: stow yabai --target=$HOME --verbose=2
    chdir: "{{ ansible_user_dir }}/.dotfiles"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
