- name: Install spacebar
  ansible.builtin.package:
    state: present
    name: cmacrae/formulae/spacebar
- name: Stow spacebar
  ansible.builtin.command:
    cmd: stow spacebar --target=$HOME --verbose=2
    chdir: "{{ ansible_user_dir }}/.dotfiles"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
