require("felixws.plugins.neotree")
require("felixws.plugins.markdown_preview")
require("felixws.plugins.vimwiki")
require("felixws.plugins.silicon")
require("felixws.plugins.lualine")
require("felixws.plugins.mini")
require("felixws.plugins.vim-rest-console")
