#!/usr/bin/env bash
alias asdf="setxkbmap us"
alias hjkl="setxkbmap de"
alias python="python3"
alias pip="pip3"
alias cdfd='cd $(find * -type d -maxdepth 4 | fzf)'
alias gitroot='cd $(git rev-parse --show-toplevel)'
alias ibrew='arch -x86_64 /usr/local/bin/brew'
alias man='MANWIDTH=$((COLUMNS > 120 ? 120 : COLUMNS)) man'
alias curlsigv4='curl -H "x-amz-security-token: $AWS_SESSION_TOKEN" --user "$AWS_ACCESS_KEY_ID":"$AWS_SECRET_ACCESS_KEY" --aws-sigv4 "aws:amz:eu-central-1:execute-api"'
