#!/usr/bin/env bash
addToPath $HOME/.rd/bin
addToPathFront /Applications/kitty.app/Contents/MacOS
#
# Set PATH, MANPATH, etc., for Homebrew.
if ! [ -f "/opt/homebrew/bin/brew)" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# pyenv
addToPathFront $HOME/.pyenv/bin
eval "$(pyenv init -)"


export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

addToPathFront $HOME/.local/scripts
addToPathFront $HOME/.local/bin
